
# Retrieving user By Id
GET http://localhost:3000/api/users/1 HTTP/1.1
###

# Retrieving reservations by user Id
GET http://localhost:3000/api/reservations/id/1 HTTP/1.1
###

# deleting reservations by user Id
DELETE  http://localhost:3000/api/reservations/410 HTTP/1.1
###

## Create new reservation (without reservationid)
POST http://localhost:3000/api/reservations/ HTTP/1.1
content-type: application/json

{
    "airplane_type": "local",
    "row": 10,
    "col":"A",
    "user_id": 1
}
###

## Register new user
POST http://localhost:3000/api/sessions/register HTTP/1.1
content-type: application/json

{
    "email": "user4@test",
    "name": "user4",
    "password": "password"
}
###

## Execute Log In
POST http://localhost:3000/api/sessions/login HTTP/1.1
content-type: application/json

{
    "username": "user@test",
    "password": "password"
}
###

## Checking if user is still logged-in.
GET http://localhost:3000/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3000/api/sessions/current HTTP/1.1
###

# Retrieving all reservations
GET http://localhost:3000/api/reservations/all HTTP/1.1
###

# 
GET http://localhost:3000/api/sessions/current HTTP/1.1
###